// setup these items for lua side
//   mouse_btn.LMB / mouse_btn.RMB / mouse_btn.MMB / mouse_btn.XB1 / mouse_btn.XB2
//   wheel_rotation.WU / wheel_rotation.WD
//
// args are generated by X-macro, which promise it is always in latest ver
//
#include <adapter.hpp>
#include <enums_list.hpp>
#include <script_binding.hpp>
#include <string_view>

extern "C"
{
#include "lua.h"
#include "lauxlib.h"
#include "lualib.h"
}

static void bind_mouse_btn(lua_State *L)
{
// generate { "LMB", mouse::LMB }, { "RMB", mouse::RMB }, ...
#define MOUSE_BTN_BIND_ITEM(name, value) {#name, mouse::name},

    static const struct
    {
        std::string_view name;
        int btn;
    } table[] = {
        MOUSE_BTN_LIST(MOUSE_BTN_BIND_ITEM)};
#undef MOUSE_BTN_BIND_ITEM

    lua_newtable(L);
    for (const auto &e : table)
    {
        lua_pushinteger(L, e.btn);
        lua_pushlstring(L, e.name.data(), e.name.size()); // push key
        lua_settable(L, -3);                              // mouse_btn[key] = <enum_val>
    }
    lua_setglobal(L, "mouse_btn");
}

static void bind_wheel_rotation(lua_State *L)
{
// generate { "WU", mouse::WU }, { "WD", mouse::WD }
#define WHEEL_ROTATION_BIND_ITEM(name, value) {#name, mouse::name},

    static const struct
    {
        std::string_view name;
        int rot;
    } table[] = {
        WHEEL_ROTATION_LIST(WHEEL_ROTATION_BIND_ITEM)};
#undef WHEEL_ROTATION_BIND_ITEM

    lua_newtable(L);
    for (const auto &e : table)
    {
        lua_pushinteger(L, e.rot);
        lua_pushlstring(L, e.name.data(), e.name.size()); // push key
        lua_settable(L, -3);                              // wheel_rotation[key] = <enum_val>
    }
    lua_setglobal(L, "wheel_rotation");
}

static void bind_keys(lua_State *L)
{
#define KEY_BIND_ITEM(v, k) {#v, k},
    const static struct
    {
        std::string_view name;
        int key;
    } table[]{
        // X(NONE, 0) is generated & bound to Lua as keys.NONE
        KEYS_LIST(KEY_BIND_ITEM)};
#undef KEY_BIND_ITEM

    lua_newtable(L);
    for (const auto &e : table)
    {
        lua_pushlstring(L, e.name.data(), e.name.size()); // push key
        lua_pushinteger(L, e.key);                        // push val
        lua_settable(L, -3);                              // keys[key] = <enum_val>
    }
    lua_setglobal(L, "keys");
}

// active this after luaL_newstate() + luaL_openlibs()(every time we goes to Lua Side)
void register_script_enums(lua_State *L)
{
    bind_mouse_btn(L);
    bind_wheel_rotation(L);
    bind_keys(L);
}