// setup these items for lua side
//   mouse_btn.LMB / mouse_btn.RMB / mouse_btn.MMB / mouse_btn.XB1 / mouse_btn.XB2
//   wheel_rotation.WU / wheel_rotation.WD
//
// args are generated by X-macro, which promise it is always in latest ver 
// 
#include <adapter.hpp>
#include <config.hpp>
#include <enums_list.hpp>

extern "C"
{
#include "lua.h"
#include "lauxlib.h"
#include "lualib.h"
}

#ifdef NULL
#undef NULL
#endif

static void bind_mouse_btn(lua_State* L)
{
    // generate { "LMB", mouse::LMB }, { "RMB", mouse::RMB }, ...
    #define MOUSE_BTN_BIND_ITEM(name, value) {#name, mouse::name},

    static const struct { const char* name; int btn; } table[] = {
        MOUSE_BTN_LIST(MOUSE_BTN_BIND_ITEM)
    };
    #undef MOUSE_BTN_BIND_ITEM

    lua_newtable(L);
    for (const auto& e : table)
    {
        lua_pushinteger(L, e.btn);
        lua_setfield(L, -2, e.name); // mouse_btn[name] = <enum_val>
    }
    lua_setglobal(L, "mouse_btn");
}

static void bind_wheel_rotation(lua_State* L)
{
    // generate { "WU", mouse::WU }, { "WD", mouse::WD }
    #define WHEEL_ROTATION_BIND_ITEM(name, value) {#name, mouse::name},

    static const struct { const char* name; int rot; } table[] = {
        WHEEL_ROTATION_LIST(WHEEL_ROTATION_BIND_ITEM)
    };
    #undef WHEEL_ROTATION_BIND_ITEM

    lua_newtable(L);
    for (const auto& e : table)
    {
        lua_pushinteger(L, e.rot);
        lua_setfield(L, -2, e.name); // wheel_rotation[name] = <enum_val>
    }
    lua_setglobal(L, "wheel_rotation");
}

// active this after luaL_newstate() + luaL_openlibs()(every time we goes to Lua Side)
void register_script_enums(lua_State* L)
{
    bind_mouse_btn(L);
    bind_wheel_rotation(L);
}