[global]
smooth_frametime_ms = 4
max_window_width = 800
max_window_height = 600
silent_launch = true

[L]
keys = ["LEFT_CONTROL", "L"]
enabled = false
type = 'inline'
[L.onActive]
val = [{ cmd = 'translate', args = [0, 32, 10], delay = 0 }]
[L.loop]
enabled = false
times = 0
delay = 0.0

[J]
keys = ["LEFT_CONTROL", "J"]
enabled = false
type = 'inline'
[J.onActive]
val = [{ cmd = 'translate', args = [90, 32, 10], delay = 0 }]
[J.loop]
enabled = false
times = 0
delay = 0.0

[H]
keys = ["LEFT_CONTROL", "H"]
enabled = false
type = 'inline'
[H.onActive]
val = [{ cmd = 'translate', args = [180, 32, 10], delay = 0 }]
[H.loop]
enabled = false
times = 0
delay = 0.0

[K]
keys = ["LEFT_CONTROL", "K"]
enabled = false
type = 'inline'
[K.onActive]
val = [{ cmd = 'translate', args = [-90, 32, 10], delay = 0 }]
[K.loop]
enabled = false
times = 0
delay = 0.0

[F1]
keys = ["F1"]
enabled = false
type = 'inline'
[F1.onActive]
val = [{ cmd = 'click', args = 'LMB', delay = 0 }]
[F1.loop]
enabled = true
times = -1
delay = 0.05

[F12]
keys = ["F12"]
enabled = false
type = 'inline'
[F12.onActive]
val = [
    { cmd = 'click', args = [
        'LMB',
    ], delay = 0.0 },
    { cmd = 'wheel', args = [
        'WU',
        1.0,
    ], delay = 100.0 },
    { cmd = 'translate', args = [
        0.0,
        32,
        10,
    ], delay = 50.0 },
]
[F12.loop]
enabled = false
times = 0
delay = 0.0
