[global]
smooth_frametime_ms = 4
max_window_width = 800
max_window_height = 600

[L]
keys = ["LEFT_CONTROL","L"]
enabled = false
type = 'inline'
val = """
    function run()
        return {
            {cmd = cmd.translate, args = {0.0, 32, 10}, delay = 0.0},
        }
    end
"""
[L.loop]
enabled = false
times = 0
delay = 0.0

[J]
keys = ["LEFT_CONTROL","J"]
enabled = false
type = 'inline'
val = """
    function run()
        return {
            {cmd = cmd.translate, args = {90.0, 32, 10}, delay = 0.0},
        }
    end
"""
[J.loop]
enabled = false
times = 0
delay = 0.0

[H]
keys = ["LEFT_CONTROL","H"]
enabled = false
type = 'inline'
val = """
    function run()
        return {
            {cmd = cmd.translate, args = {180.0, 32, 10}, delay = 0.0},
        }
    end
"""
[H.loop]
enabled = false
times = 0
delay = 0.0

[K]
keys = ["LEFT_CONTROL","K"]
enabled = false
type = 'inline'
val = """
    function run()
        return {
            {cmd = cmd.translate, args = {270.0, 32, 10}, delay = 0.0},
        }
    end
"""
[K.loop]
enabled = false
times = 0
delay = 0.0

[F1]
keys = ["F1"]
enabled = false
type = 'inline'
val = """
    function run()
        return {
            {cmd = cmd.click, args = {mouse_btn.LMB}, delay = 0.0},
        }
    end
"""
[F1.loop]
enabled = true
times = -1
delay = 0.05

[F12]
keys = ["F12"]
enabled = false
type = 'inline'
val = """
    function run()
        -- a complex macro: multiple instructions, each with an explicit delay
        return {
            {cmd = cmd.click,     args = {mouse_btn.LMB},         delay = 0.0},
            {cmd = cmd.wheel,     args = {wheel_rotation.WU, 1.0}, delay = 100.0},
            {cmd = cmd.translate, args = {0.0, 32, 10},           delay = 50.0},
        }
    end
"""
[F12.loop]
enabled = false
times = 0
delay = 0.0